import { Builder } from '../../builder';
import { IAbode } from '../Abode';
import { IInput, IOption, ISelect } from '../Field/types';
import { ICheckbox } from '../Checkbox/types';
import { ShippingState } from './container';

export const shippingState = Builder<ShippingState>()
  .delivery(
    Builder<IAbode>()
      .forname(Builder<IInput>().id('forname2').value('').valid(false).build())
      .surname(Builder<IInput>().id('surname2').value('').valid(false).build())
      .street(Builder<IInput>().id('street2').value('').valid(false).build())
      .streetNo(
        Builder<IInput>().id('streetNo2').value('').valid(false).build()
      )
      .postcode(
        Builder<IInput>().id('postcode2').value('').valid(false).build()
      )
      .cities(
        Builder<ISelect>()
          .id('city2')
          .value('')
          .options([
            Builder<IOption>()
              .id('prague')
              .value('Prague')
              .title('Prague')
              .build(),
          ])
          .build()
      )
      .countries(
        Builder<ISelect>()
          .id('country2')
          .value('')
          .options([
            Builder<IOption>()
              .id('czechia')
              .value('Czechia')
              .title('Czechia')
              .build(),
          ])
          .build()
      )
      .build()
  )
  .invoicing(
    Builder<IAbode>()
      .forname(Builder<IInput>().id('forname1').value('').valid(false).build())
      .surname(Builder<IInput>().id('surname1').value('').valid(false).build())
      .company(Builder<IInput>().id('company').value('').valid(false).build())
      .vat(Builder<IInput>().id('vat').value('').valid(false).build())
      .street(Builder<IInput>().id('street1').value('').valid(false).build())
      .streetNo(
        Builder<IInput>().id('streetNo1').value('').valid(false).build()
      )
      .postcode(
        Builder<IInput>().id('postcode1').value('').valid(false).build()
      )
      .cities(
        Builder<ISelect>()
          .id('city1')
          .value('')
          .options([
            Builder<IOption>()
              .id('prague')
              .title('Prague')
              .value('prague')
              .build(),
          ])
          .build()
      )
      .countries(
        Builder<ISelect>()
          .id('country1')
          .value('')
          .options([
            Builder<IOption>()
              .id('czechia')
              .title('Czechia')
              .value('czechia')
              .build(),
          ])
          .build()
      )
      .build()
  )
  .company(Builder<ICheckbox>().id('company').checked(true).build())
  .data(Builder<ICheckbox>().id('data').checked(false).build())
  .terms(Builder<ICheckbox>().id('terms').checked(false).build())
  .build();
