export enum JustifyContent {
  START = 'justify-content-start',
  END = 'justify-content-end',
  CENTER = 'justify-content-center',
  BETWEEN = 'justify-content-between',
  AROUND = 'justify-content-around',
  SM_START = 'justify-content-sm-start',
  SM_END = 'justify-content-sm-end',
  SM_CENTER = 'justify-content-sm-center',
  SM_BETWEEN = 'justify-content-sm-between',
  SM_AROUND = 'justify-content-sm-around',
  MD_START = 'justify-content-md-start',
  MD_END = 'justify-content-md-end',
  MD_CENTER = 'justify-content-md-center',
  MD_BETWEEN = 'justify-content-md-between',
  MD_AROUND = 'justify-content-md-around',
  LG_START = 'justify-content-lg-start',
  LG_END = 'justify-content-lg-end',
  LG_CENTER = 'justify-content-lg-center',
  LG_BETWEEN = 'justify-content-lg-between',
  LG_AROUND = 'justify-content-lg-around',
  XL_START = 'justify-content-xl-start',
  XL_END = 'justify-content-xl-end',
  XL_CENTER = 'justify-content-xl-center',
  XL_BETWEEN = 'justify-content-xl-between',
  XL_AROUND = 'justify-content-xl-around',
}
