export enum TextAlign {
  CENTER = 'text-center',
  LEFT = 'text-left',
  RIGHT = 'text-right',
  XS_CENTER = 'text-xs-center',
  SM_CENTER = 'text-sm-center',
  MD_CENTER = 'text-md-center',
  LG_CENTER = 'text-lg-center',
  XL_CENTER = 'text-xl-center',
  XS_LEFT = 'text-xs-left',
  SM_LEFT = 'text-sm-left',
  MD_LEFT = 'text-md-left',
  LG_LEFT = 'text-lg-left',
  XL_LEFT = 'text-xl-left',
  XS_RIGHT = 'text-xs-right',
  SM_RIGHT = 'text-sm-right',
  MD_RIGHT = 'text-md-right',
  LG_RIGHT = 'text-lg-right',
  XL_RIGHT = 'text-xl-right',
}
